name: Mojank
main: cc.funkemunky.fixer.Mojank
<<<<<<< HEAD
<<<<<<< HEAD
author: funkemunky
version: 0.0.1
=======
version: 1.1-b1
author: funkemunky
softdepend: [ProtocolLib]
>>>>>>> 6dfd4c36e27508f96a9a7ff4d9ddf83d507eb43a
=======
version: 1.3
author: funkemunky
softdepend: [ProtocolLib]
>>>>>>> 5f287e9ce1f32f5f45e481fae11d05d10b0f8909
